"""empty message

Revision ID: 1fd9ff7ab061
Revises: 95ed2600cfd4
Create Date: 2025-02-25 20:25:38.751921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd9ff7ab061'
down_revision = '95ed2600cfd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.drop_index('ix_post_timestap')
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('timestap')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestap', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.create_index('ix_post_timestap', ['timestap'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
